name: Build Single Course Page

on:
  workflow_dispatch:
    inputs:
      course_name:
        description: 'Name of the course'
        required: true
        # default: 'AUTO1000'  # Default value, in case no input is provided

jobs:
  example_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print course name
        run: echo "Course name: ${{ github.event.inputs.course_name }}"
