name: Daily Report

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-report:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive
          fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run the script
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        ORG_NAME: HITSZ-OpenAuto
        NEWS_TYPE: daily
      run: |
        python scripts/gen_news.py

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: 'content'
        default_author: github_actions
