name: 获取公开仓库列表

on:
  push:

  workflow_dispatch:  # 手动触发

jobs:
  get-repos:
    runs-on: ubuntu-latest

    steps:
      - name: 获取组织的公开仓库
        run: |
          curl -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/HITSZ-OpenAuto/repos?type=public" > repos.json

      - name: 解析仓库并保存为环境变量
        id: parse_repos
        run: |
          # 使用 jq 解析 JSON 并将仓库名称提取为数组
          repos=$(jq -r '.[].name' repos.json | jq -R -s -c 'split("\n")[:-1]')
          echo "repos_array=$repos" >> $GITHUB_ENV  # 将数组保存到环境变量

      - name: 使用解析后的仓库数组
        run: |
          # 将 JSON 数组解析为单个值的列表
          repos=$(echo "${{ env.repos_array }}" | jq -r '.[]')
          echo repos
          # # 遍历数组并打印每个值
          # for repo in $repos; do
          #   echo $repo 
          # done
