name: Weekly Commit Report

on:
  schedule:
    - cron: '30 10 * * 5'  # This sets the workflow to run at 10:00 UTC+0 every Friday (6 PM Beijing time)
  workflow_dispatch:  # This allows you to manually trigger the workflow

jobs:
  generate-report:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      id-token: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: recursive
          fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install -r scripts/requirements.txt

    - name: Run the script
      env:
        TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        ORG_NAME: HITSZ-OpenAuto
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Add your OpenAI API key as a secret
        NEWS_TYPE: weekly
      run: |
        python scripts/gen_news.py

    # - name: Commit and push changes
    #   uses: EndBug/add-and-commit@v9
    #   with:
    #     add: 'content'
    #     default_author: github_actions

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        commit-message: 'docs: new weekly report'
        branch: weekly-report
        title: 'Weekly Report'
        body: Weekly report for the week has been generated, please review and merge.
        labels: weekly-report
        team-reviewers: auto-core
